In [1]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [3]:
df.target.value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [6]:
# indepedent and dependent
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [7]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test, y_train, y_test= train_test_split(x,y,test_size=0.30, random_state=41)

In [18]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
686,52,1,0,128,204,1,1,156,1,1.0,1,0,0
397,40,1,0,110,167,0,0,114,1,2.0,1,0,3
312,70,1,2,160,269,0,1,112,1,2.9,1,1,3
345,66,1,1,160,246,0,1,120,1,0.0,1,3,1
821,62,0,0,140,268,0,0,160,0,3.6,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,48,0,2,130,275,0,1,139,0,0.2,2,0,2
80,50,1,2,140,233,0,1,163,0,0.6,1,1,3
994,59,1,0,110,239,0,0,142,1,1.2,1,1,3
908,62,1,0,120,267,0,1,99,1,1.8,1,2,3
931,40,1,0,152,223,0,1,181,0,0.0,2,0,3

In [19]:
df.shape

(1025, 14)

In [20]:
dt= DecisionTreeClassifier()

In [21]:
dt.fit(x_train, y_train)
y_pred= dt.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score

In [23]:
confusion_matrix(y_pred, y_test)

array([[127,   3],
       [  0, 178]], dtype=int64)

In [24]:
recall_score(y_test, y_pred)

0.9834254143646409

In [ ]:
# post pruning and pre-pruning , and how to make tree....